<a href="https://colab.research.google.com/github/battlestar006/First-File/blob/main/Libraries2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
class calculator:
  def add(self, x,y):
   return x+y
  def mul(self, x,y):
   return x*y
obj = calculator()
print(obj.add(10,20))
print(obj.mul(10,20))

30
200


In [ ]:
#create array to store value [90,67,36,22],[22,26,78,99]
import numpy as np
arr=np.array([[90,67,36,22],[22,26,78,99]])
print(arr)
print("type of array",type(arr))
print("no. of element",arr.size)
print("row and colume",arr.shape)
print("dimension of array",arr.ndim)
print( arr.dtype)


[[[[90 67 36 22]
   [22 26 78 99]]]]
type of array <class 'numpy.ndarray'>
no. of element 8
row and colume (1, 1, 2, 4)
dimension of array 4
datatype int64


arr1=np.array([10,20,30])
print('sum',np.sum(arr1))
print('max',np.max(arr1))
print('min',np.min(arr1))
print('mean',np.mean(arr1))
print('median',np.median(arr1))
print('std',np.std(arr1))

In [ ]:
arr=np.arange(1,100)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
arr =np.arange(1,10)
arr

arr=np.arange(2,40,2)
arr

In [ ]:
arr = np.arange(5,51,5)
arr

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

arr = np.arange(5,51,5),np.arange(5,51,5)

arr

In [ ]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

arr = np.arange(1,15).reshape(7,2)
arr

In [ ]:
arr=np.arange(2,21,2),np.arange(2,21,2)
arr

(array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]),
 array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]))

In [ ]:
arr=np.arange(1,25).reshape(1,24)
print(arr)
ar=np.arange(1,25).reshape(2,12)
print(ar)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [ ]:
ar=np.arange(1,7).reshape(1,2,3)
ar


array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
arr=np.arange(1,13).reshape(3,2,2)
arr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

### **linspace**

**it used to generated equal spaced between the given rnage by default is 50 value

In [ ]:
import numpy as np
arr =np.linspace(1,100,20 ,retstep)
arr


array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])


# Random function

randn
rand
randint
It is used to generate an array with random integers between given range

In [ ]:
arr = np.random.randint(1,100)
arr

89

In [ ]:
arr = np.random.randint(1,100,10)
arr

array([66, 86, 20,  7, 42, 18, 22,  3, 18, 78])

In [ ]:
arr= np.random.randn(100)
arr

array([-5.60370543e-01, -2.08988781e+00, -4.51488494e-01,  3.95262909e-01,
        6.97444159e-01,  3.35041995e-01, -7.18838264e-02, -3.91608729e-01,
       -1.47519621e+00,  3.35821778e-01,  7.99197790e-04, -4.09587189e-01,
        1.81173435e-01, -1.78874208e-01, -4.93611917e-01,  1.32704620e+00,
       -1.72654101e-01,  6.44485964e-01, -1.27315767e+00,  7.29694028e-01,
       -2.77006149e-02,  4.00480721e-01,  7.74894957e-01,  1.00986809e+00,
        4.67859338e-02, -1.19440851e+00,  1.96941103e-01, -1.21307055e+00,
        1.10087012e+00, -1.08661357e+00,  1.16560519e+00, -2.03008989e+00,
        3.07707193e-01, -8.56505154e-01,  1.13943565e+00,  1.23575499e+00,
       -1.62347516e+00, -1.53318885e+00,  1.29359573e-01,  1.52547821e+00,
        8.05661954e-01, -7.19401336e-01, -4.85118991e-01,  6.47214895e-01,
        1.24623307e-01, -4.65951542e-01, -2.66107932e-01,  3.20238065e-01,
       -1.27514933e+00,  2.79036794e+00, -3.13343068e-01, -1.84451261e+00,
       -1.95631270e+00,  

In [ ]:
import numpy as np
arr = np.random.rand(100,1000,20)
arr

array([[[0.68502909, 0.24482883, 0.82290214, ..., 0.429967  ,
         0.15672723, 0.78032006],
        [0.04845791, 0.69586353, 0.40662784, ..., 0.27342698,
         0.15591983, 0.23238227],
        [0.77201046, 0.4755119 , 0.46446287, ..., 0.15881409,
         0.14024418, 0.63323425],
        ...,
        [0.83285031, 0.11272469, 0.32935461, ..., 0.14479309,
         0.9596984 , 0.09978807],
        [0.40229806, 0.71978803, 0.9742569 , ..., 0.42701883,
         0.725353  , 0.76395429],
        [0.57475014, 0.81442298, 0.03096519, ..., 0.03653944,
         0.38864475, 0.90717406]],

       [[0.83656791, 0.49315442, 0.45215949, ..., 0.02667277,
         0.1609152 , 0.94518913],
        [0.76565254, 0.30440895, 0.88568241, ..., 0.18035604,
         0.13028298, 0.86062028],
        [0.9579593 , 0.15799498, 0.28273515, ..., 0.7639207 ,
         0.19767118, 0.85722098],
        ...,
        [0.33056923, 0.34821231, 0.20508557, ..., 0.9789331 ,
         0.0705424 , 0.61892333],
        [0.3

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[0]# fetch 1 row
arr[2]# fetch 3 row
arr[0::2]# fetch 1 and 2 row
arr[:,[2]]# fetch 1 and 3 row
arr[:,[1,2]]# fetch 1 and 2 column

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
'''
[1,2]
[4,5]
'''
arr[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [ ]:
'''
2,3
'''
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])